language: java
sudo: false
before_install:
  - "git clone https://github.com/geomajas/geomajas-build-tools target/geomajas-build-tools -q"
  - "export MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=2048m'"
jdk:
  - oraclejdk7
cache:
  directories:
  - $HOME/.m2
install: mvn dependency:go-offline -q --settings target/geomajas-build-tools/settings.xml
script: mvn test -B -V --settings target/geomajas-build-tools/settings.xml
